#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")[ClassVersion("1.0.0"), FriendlyName("cSqlServerInstall")] class PSHOrg_cSqlServerInstall : OMI_BaseResource{    [key, Description("The name of sql instance.")] string InstanceName;    [required, Description("The share path of sql server software.")] string SourcePath;    [write,EmbeddedInstance("MSFT_Credential"),     Description("The credential that vm could use to access net share of sql server software.")]     string SourcePathCredential;    [write, Description("List of names of Sql Server features to install")] string Features;    [required,EmbeddedInstance("MSFT_Credential"), Description("Sql sa credential")] string SqlAdministratorCredential;};

