[ClassVersion("1.0.0"), FriendlyName("FirewallRule")]
class StackExchange_FirewallRule :  OMI_BaseResource
{
	[Key] string DisplayName;
	[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
	[write,ValueMap{"Allow", "Block"},Values{"Allow", "Block"}] string Action;
	[write] string Description;
	[write,ValueMap{"Inbound", "Outbound"},Values{"Inbound", "Outbound"}] string Direction;
	[write,ValueMap{"Any", "ProximityApps", "ProximitySharing"},Values{"Any", "ProximityApps", "ProximitySharing"}] string DynamicTransport;
	[write,ValueMap{"Block", "Allow", "DeferToUser", "DeferToApp"},Values{"Block", "Allow", "DeferToUser", "DeferToApp"}] string EdgeTraversalPolicy;
	[write,ValueMap{"True", "False"},Values{"True", "False"}] string Enabled;
	[write,ValueMap{"NotRequired", "Required", "Dynamic"},Values{"NotRequired", "Required", "Dynamic"}] string Encryption;
	[write] string IcmpType[];
	[write] string InterfaceAlias[];
	[write,ValueMap{"Any", "Wired", "Wireless", "RemoteAccess"},Values{"Any", "Wired", "Wireless", "RemoteAccess"}] string InterfaceType;
	[write] string LocalAddress[];
	[write] string LocalPort[];
	[write] string LocalUser;
	[write,ValueMap{"Any", "Domain", "Private", "Public", "NotApplicable"},Values{"Any", "Domain", "Private", "Public", "NotApplicable"}] string Profile;
	[write] string Program;
	[write] string Protocol;
	[write] string RemoteAddress[];
	[write] string RemoteMachine;
	[write] string RemoteUser;
	[write] string Service;
};


