#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0"), FriendlyName("cSqlHAEndPoint")] 
class cSqlHAEndPoint : OMI_BaseResource
{
    [key, Description("Name of Sql Instance.")] string InstanceName;

    [required, Description("Windows Account that could access the HA database mirroring endpoing.")] string AllowedUser;
    [key, Description("Unique name for HA database mirroring endpoint of the sql instance.")] string Name;
    [write, Description("The single port number(nnnn) on which the Sql HA to listen to.")] Uint32 PortNumber;
};


