[version("1.0.0"), FriendlyName("ExecutionPolicy")]
class ExecutionPolicy : MSFT_BaseResourceConfiguration
{
	[Key] string Name;
	[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
