[ClassVersion("1.0.0"), FriendlyName("cDNSServerAddress")] 
class PSCommunity_cDNSServerAddress : OMI_BaseResource
{
  [Required] string Address[];
  [Key] string InterfaceAlias;
  [Write,ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;
};
