[ClassVersion("1.0.0.0"), FriendlyName("cVMSwitch")]
class PSHOrg_cVMSwitch : OMI_BaseResource
{
	[Key, Description("Name of the VM Switch")] String Name;
	[Key, Description("Type of switch"), ValueMap{"External","Internal","Private"}, Values{"External","Internal","Private"}] String Type;
	[Write, Description("Network adapter name for external switch type")] String NetAdapterName;
	[Write, Description("Specify is the VM host has access to the physical NIC")] Boolean AllowManagementOS;
	[Write, Description("Whether switch should be present or absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Read, Description("Unique ID for the switch")] String Id;
	[Read, Description("Description of the network interface")] String NetAdapterInterfaceDescription;
};



