[ClassVersion("1.0.0"), FriendlyName("cDSCWebService")] 
class PSHOrg_cDSCWebService : OMI_BaseResource
{
  [Key] string EndpointName;
  [required] string CertificateThumbPrint;
  [write] uint32 Port;
  [write] string PhysicalPath;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write,ValueMap{"Started","Stopped"},Values{"Started", "Stopped"}] string State;
  [write] string ModulePath;
  [write] string ConfigurationPath;
  [write] boolean IsComplianceServer;
  [read] string DSCServerUrl;  
};

