#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0"), FriendlyName("cSqlHAGroup")] 
class cSqlHAGroup : OMI_BaseResource
{
    [key, Description("The name of sql availability group")] string Name;
    [required, Description("Array of databases on the local sql instance. Each database can belong to only one HA group.")] string Database[];
    [required, Description("The name of windows failover cluster for the availability group")] string ClusterName;
    [required, Description("The net share for Sql replication initialization")] string DatabaseBackupPath;
    [required, Description("Name of sql instance")] string InstanceName;
    [required, Description("Name of EndPoint to access High Availability sql instance.")] string EndPointName;

    [Required, EmbeddedInstance("MSFT_Credential"), Description("Domain credential could get list of cluster nodes.")] 
    String DomainCredential;

    [Required, EmbeddedInstance("MSFT_Credential"), Description("Sql sa credential.")] 
    String SqlAdministratorCredential;
};


