#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0"), FriendlyName("cCluster")] 
class PSHOrg_cCluster : OMI_BaseResource
{
    [key, Description("Name of the Cluster")] string Name;
    [required, Description("StaticIPAddress of the Cluster")] string StaticIPAddress;
    
    [required, EmbeddedInstance("MSFT_Credential"), Description("Credential to create the cluster")] 
    String DomainAdministratorCredential;
};


