[ClassVersion("1.0.0"), FriendlyName("cVHD")]
class PSHOrg_cVHD : OMI_BaseResource
{
	[Key, Description("Name of the VHD File")] String Name;
	[Key, Description("Folder where the VHD will be created")] String Path;
	[Write, Description("Parent VHD file path, for differencing disk")] String ParentPath;
	[Write, Description("Maximum size of Vhd to be created")] Uint64 MaximumSizeBytes;
	[Write, Description("Virtual disk format - Vhd or Vhdx"), ValueMap{"Vhd","Vhdx"}, Values{"Vhd","Vhdx"}] String Generation;
	[Write, Description("Should the VHD be created or deleted"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Read, Description("Virtual Disk Identifier")] String ID;
	[Read, Description("Type of Vhd - Dynamic, Fixed, Differencing")] String Type;
	[Read, Description("Current size of the VHD")] Uint64 FileSizeBytes;
	[Read, Description("Is the VHD attached to a VM or not")] Boolean IsAttached;
};

