[ClassVersion("1.0"), FriendlyName("NetworkAdapter")]
class NetworkAdapter : OMI_BaseResource
{
	[Key] string Name;
	[Key] string Description;
	[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
