
[ClassVersion("1.0.0.0"), FriendlyName("PSHOrg_cVMHost")]
class PSHOrg_cVMHost : OMI_BaseResource
{
	[Key] String VMHost;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
	[Write] String VirtualDiskPath;
	[Write] String VirtualMachinePath;
	[Write, ValueMap{"True","False","","0","1"}, Values{"True","False","","0","1"}] String VirtualMachineMigration;
	[Write, ValueMap{"True","False","","0","1"}, Values{"True","False","","0","1"}] String EnhancedSessionMode;
	[Read] Boolean HyperVPowerShell;
};



