#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0"),FriendlyName("Script")] 
class cScriptResource : OMI_BaseResource
{
  [Key] string GetScript;
  [Key] string SetScript;
  [Key] string TestScript;
  [Write, EmbeddedInstance("MSFT_KeyValuePair")] String GetScriptParam;
  [Write, EmbeddedInstance("MSFT_KeyValuePair")] String SetScriptParam;
  [Write, EmbeddedInstance("MSFT_KeyValuePair")] String TestScriptParam;
  [write,EmbeddedInstance("MSFT_Credential")] string Credential;
  [Read] string Result;
};



