
[ClassVersion("1.0.0.0")]
Class PSHOrg_cFileDirectory
{
  [Required] string DestinationPath;
  [Write] string SourcePath;
  [Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [Write,ValueMap{"File", "Directory"},Values{"File", "Directory"}] string Type;
  [Write] boolean Recurse;
  [Write] boolean Force ;
  [write] string Content;
  [Write,ValueMap{"ReadOnly", "Hidden", "System", "Archive"},Values{"ReadOnly", "Hidden", "System", "Archive"}] string Attributes[];
};

[ClassVersion("1.0.0.0"), FriendlyName("cVhdFile")]
class PSHOrg_cVhdFileDirectory : OMI_BaseResource
{
	[Key, Description("Path to the VHD")] String VhdPath;
	[Required, EmbeddedInstance("PSHOrg_cFileDirectory"), Description("The FileDirectory objects to copy to the VHD")] String FileDirectory[];
};



