
[ClassVersion("1.0.0"), FriendlyName("cComputer")] 
class PSHOrg_cComputer : OMI_BaseResource
{
    [key] string Name;

    [write] string DomainName;
    
    [write,EmbeddedInstance("MSFT_Credential")] String Credential;

    [write] string WorkGroupName;
};


