[ClassVersion("1.0"), FriendlyName("ScheduledTask")]
class StackExchange_ScheduledTask : OMI_BaseResource
{
[Key] string Name;
[Key] string FilePath;
[write] string At;
[write] sint32 Hours;
[write] sint32 Minutes;
[write] boolean Once;
[write] sint32 DaysInterval;
[write] boolean Daily;
[write] string DaysOfWeek[];
[write] boolean Weekly;
[write,EmbeddedInstance("MSFT_Credential")] string Credential;
[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};


