[ClassVersion("1.0"), FriendlyName("NetworkAdapter")]
class StackExchange_NetworkAdapter : OMI_BaseResource
{
	[Key] string Name;
	[Key] string Description;
    [write] string TeamName;
	[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};


