#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0"), FriendlyName("cSqlHAService")] 
class cSqlHAService : OMI_BaseResource
{
    [key, Description("The name of Sql instance.")] 
    string InstanceName;
    
    [required, EmbeddedInstance("MSFT_Credential"), Description("Sql sa credential")]
    string SqlAdministratorCredential;
    
    [required, EmbeddedInstance("MSFT_Credential"), Description("Domain credential to run sql service")] 
    String ServiceCredential;
};


