[ClassVersion("1.0.0"), FriendlyName("SetExecutionPolicy")]
class StackExchange_SetExecutionPolicy :  OMI_BaseResource
{
	[Key,ValueMap{"Restricted", "AllSigned", "RemoteSigned", "Unrestricted"},Values{"Restricted", "AllSigned", "RemoteSigned", "Unrestricted"}] string Name;
	[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};


