#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0.0"), FriendlyName("cWaitForSqlHAGroup")]
class cWaitForSqlHAGroup : OMI_BaseResource
{
    [Key, Description("The name of Sql High Availability group")] String Name;
    [required, Description("The name of windows failover cluster for the availability group.")] string ClusterName;
    [Write, Description("Interval to check the HA group existency")] Uint64 RetryIntervalSec;
    [Write, Description("Maximum number of retries to check HA group existency")] Uint32 RetryCount;

    [required, Description("The name of sql instance.")] string InstanceName;

    [Required, EmbeddedInstance("MSFT_Credential"), Description("Domain credential could get list of cluster nodes.")] 
    String DomainCredential;

    [Required, EmbeddedInstance("MSFT_Credential"), Description("Sql sa credential")] 
    String SqlAdministratorCredential;
};

