[ClassVersion("1.0"), FriendlyName("CertificateStore")]
class StackExchange_CertificateStore : OMI_BaseResource
{
[Key] string Name;
[Key] string Path;
[write,ValueMap{"LocalMachine", "CurrentUser"},Values{"LocalMachine", "CurrentUser"}] string Location;
[write] string Store;
[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};


