#
# Module manifest for module 'DscConfiguration'
#
# Generated by: Steven
#
# Generated on: 4/14/2014
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DscConfiguration.psm1'

# Version number of this module.
ModuleVersion = '1.5.1.0'

# ID used to uniquely identify this module
GUID = '0b48e2a7-dcd7-4888-95ec-f80d6fca03b6'

# Author of this module
Author = 'Steven Murawski'

# Company or vendor of this module
CompanyName = 'Stack Exchange'

# Copyright statement for this module
Copyright = '(c) 2014 Steven. All rights reserved.'

# Description of the functionality provided by this module
# Description = ''

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Get-DscConfigurationData', 
                    'New-DscNodeMetadata',
                    'New-DscServiceMetadata',
                    'New-DscSiteMetadata',
                    'Add-DscEncryptedPassword', 
                    'Get-DscEncryptedPassword',
                    'Set-DscConfigurationDataPath', 
                    'Get-DscConfigurationDataPath',
                    'New-DscConfigurationDataStore'

# Cmdlets to export from this module
#CmdletsToExport = '*'

# Variables to export from this module
#VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport =   'Add-EncryptedPassword',                     
                    'Set-ConfigurationDataPath', 
                    'Get-ConfigurationDataPath'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


