[ClassVersion("1.0.0"), FriendlyName("Pagefile")]
class StackExchange_Pagefile :  OMI_BaseResource
{
	[Key] sint64 InitialSize;
	[Key] sint64 MaximumSize;
	[write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};


